server:
  port: 8080

spring:
  application:
    name: Image Gallery API
    
  datasource:
    url: jdbc:h2:mem:image_gallery
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
cloud:
  aws:
    region: ${AWS_REGION:us-east-1}
    s3:
      bucket: ${AWS_BUCKET_NAME:aabucket2000}