name: CI/CD to AWS EB with Test Reporting

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests
        run: mvn clean test

      - name: Generate HTML test report
        run: mvn surefire-report:report

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload report to GitHub Pages
        uses: actions/deploy-pages@v4
        
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Zip application files
        run: zip -r application.zip target/*.jar

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: Application Build
          path: application.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: Application Build
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: github-${{ github.run_id }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: application.zip
